kind: PersistentVolume
apiVersion: v1
metadata:
  name: compile-worker-share
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/workers"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compile-worker-share-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
