apiVersion: v1
kind: Service
metadata:
  name: event-store-svc
  labels:
    app: event-store-svc
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: event-store-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-store-deployment
spec:
  selector:
    matchLabels:
      app: event-store-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: event-store-svc
    spec:
      containers:
      - image: redis:7.0.0
        name: redis
        ports:
        - containerPort: 6379
          name: event-store-app
        volumeMounts:
        - name: event-store-volume
          mountPath: "/redis-master-data"
      volumes:
      - name: event-store-volume
        persistentVolumeClaim:
          claimName: event-store-pv-claim
