apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: minio-svc
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  selector:
    matchLabels:
      app: minio-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio-svc
    spec:
      containers:
      - image: minio/minio:RELEASE.2022-06-03T01-40-53Z.fips
        args:
        - server
        - /mnt/data/minio
        name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio_pass"
        ports:
        - containerPort: 9000
          hostPort: 9000
          name: minio-app
        volumeMounts:
        - name: minio-volume
          mountPath: "/mnt/data/minio"
      volumes:
      - name: minio-volume
        persistentVolumeClaim:
          claimName: minio-pv-claim
