apiVersion: v1
kind: Service
metadata:
  name: resize-projector
  labels:
    app: resize-projector
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: resize-projector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resize-projector-deployment
spec:
  selector:
    matchLabels:
      app: resize-projector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: resize-projector
    spec:
      containers:
      - image: redis:7.0.0
        name: redis
        ports:
        - containerPort: 6379
          name: resize-project
      - image: ghcr.io/cs-muic/scalable-p2-scalable-t3-dartrix/resize-projection:latest
        name: resize-projector
      imagePullSecrets:
      - name: secret
