apiVersion: v1
kind: Service
metadata:
  name: status-projector
  labels:
    app: status-projector
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: status-projector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-projector-deployment
spec:
  selector:
    matchLabels:
      app: status-projector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: status-projector
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        ports:
        - containerPort: 3306
          name: status-report
        env:
        - name: MYSQL_DATABASE
          value: status
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: pass
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: 'yes'       
      - image: ghcr.io/cs-muic/scalable-p2-scalable-t3-dartrix/status-reporter-projection:latest
        name: status-projector
      imagePullSecrets:
      - name: secret
