apiVersion: v1
kind: Service
metadata:
  name: web-controller
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: web-controller
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-controller-deployment
spec:
  selector:
    matchLabels:
      app: web-controller
  template:
    metadata:
      labels:
        app: web-controller
    spec:
      containers:
      - image: ghcr.io/cs-muic/scalable-p2-scalable-t3-dartrix/web-controller:latest
        name: web-controller
        ports:
        - containerPort: 8080
          name: web-controller
      imagePullSecrets:
      - name: secret
