name: Build Resize Worker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ workers/resize/** ]
    
env:
  REGISTRY: ghcr.io
  BASE_IMG_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: [lol]
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Log in to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get short SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Check short SHA
      run: echo ${{ steps.vars.outputs.sha_short }}
    - name: Build docker image
      run: |
        cd workers/resize && \
        docker build . --file Dockerfile \
        --tag ghcr.io/${{ env.BASE_IMG_NAME }}/resize-worker:${{ steps.vars.outputs.sha_short }} \
        --tag ghcr.io/${{ env.BASE_IMG_NAME }}/resize-worker:latest
    - name: Publish images
      run: |
          docker push ghcr.io/${{ env.BASE_IMG_NAME }}/resize-worker:${{ steps.vars.outputs.sha_short }}
          docker push ghcr.io/${{ env.BASE_IMG_NAME }}/resize-worker:latest
