name: Build Thumbnail Maker Image

on:
  push:
    branches: [ main ]
    paths: [ scripts/** ]
    
env:
  REGISTRY: ghcr.io
  BASE_IMG_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Log in to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get short SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Check short SHA
      run: echo ${{ steps.vars.outputs.sha_short }}
    - name: Build docker image
      run: |
        cd backend && \
        docker build . --file Dockerfile \
        --tag ghcr.io/${{ env.BASE_IMG_NAME }}/thumbnail_maker:${{ steps.vars.outputs.sha_short }} \
        --tag ghcr.io/${{ env.BASE_IMG_NAME }}/thumbnail_maker:latest
    - name: Publish images
      run: |
          docker push ghcr.io/${{ env.BASE_IMG_NAME }}/thumbnail_maker:${{ steps.vars.outputs.sha_short }}
          docker push ghcr.io/${{ env.BASE_IMG_NAME }}/thumbnail_maker:latest
